services:
  note_rag:
    build: .
    volumes:
      - ./app:/app
    depends_on:
      - chrome
    environment:
      - NOTE_USER_ID=hinataptyan

  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2g
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
